#!/bin/bash

echo "🔍 Testing Cross-Device Restaurant Registration & Login"
echo "======================================================"

echo "📱 Checking emulator connections..."
adb devices

echo ""
echo "🧪 CROSS-DEVICE RESTAURANT SYNC TEST"
echo "===================================="
echo ""
echo "📋 TEST INSTRUCTIONS:"
echo "====================="
echo ""
echo "Step 1: Register Restaurant on Emulator 5554"
echo "--------------------------------------------"
echo "1. On Emulator 5554 (Pixel Tablet):"
echo "   - Open the POS app"
echo "   - Go to 'Register Restaurant' tab"
echo "   - Fill in these details:"
echo "     • Restaurant Name: 'Cross Test Restaurant'"
echo "     • Business Type: 'Restaurant'"
echo "     • Address: '456 Test Street'"
echo "     • Phone: '+1-555-0456'"
echo "     • Email: 'crosstest@restaurant.com'"
echo "     • Admin User ID: 'crosstest'"
echo "     • Admin Password: 'crosstest123'"
echo "   - Click 'Register Restaurant'"
echo "   - Wait for success message"
echo ""
echo "Step 2: Login on Emulator 5556"
echo "-------------------------------"
echo "2. On Emulator 5556 (Medium Phone):"
echo "   - Open the POS app"
echo "   - Go to 'Login' tab"
echo "   - Enter these credentials:"
echo "     • Restaurant Email: 'crosstest@restaurant.com'"
echo "     • User ID: 'crosstest'"
echo "     • Password: 'crosstest123'"
echo "   - Click 'Login'"
echo ""
echo "Step 3: Verify Cross-Device Sync"
echo "--------------------------------"
echo "3. Expected Results:"
echo "   ✅ Emulator 5556 should successfully login"
echo "   ✅ Should see 'Cross Test Restaurant' dashboard"
echo "   ✅ Should NOT see 'Restaurant not found' error"
echo ""
echo "Step 4: Test Reverse Direction"
echo "------------------------------"
echo "4. On Emulator 5556:"
echo "   - Go to 'Register Restaurant' tab"
echo "   - Register another restaurant:"
echo "     • Restaurant Name: 'Reverse Test Restaurant'"
echo "     • Email: 'reversetest@restaurant.com'"
echo "     • Admin User ID: 'reversetest'"
echo "     • Admin Password: 'reversetest123'"
echo ""
echo "5. On Emulator 5554:"
echo "   - Try to login with:"
echo "     • Restaurant Email: 'reversetest@restaurant.com'"
echo "     • User ID: 'reversetest'"
echo "     • Password: 'reversetest123'"
echo ""
echo "🔍 MONITORING LOGS:"
echo "==================="
echo "To monitor the sync process, run:"
echo "adb -s emulator-5554 logcat -s 'flutter' | grep -i 'firebase\|restaurant\|sync'"
echo "adb -s emulator-5556 logcat -s 'flutter' | grep -i 'firebase\|restaurant\|sync'"
echo ""
echo "🎯 SUCCESS CRITERIA:"
echo "==================="
echo "✅ Restaurant registered on one device appears on other device"
echo "✅ Login works on both devices with same credentials"
echo "✅ No 'Restaurant not found' errors"
echo "✅ Firebase sync messages in logs"
echo ""
echo "❌ If test fails:"
echo "================="
echo "1. Check Firebase connectivity"
echo "2. Check app logs for error messages"
echo "3. Verify restaurant data in Firebase"
echo "4. Run: source firebase_env/bin/activate && python3 check_and_restore_data.py"
echo ""
echo "🚀 Ready to test cross-device restaurant sync!" 