#!/bin/bash

echo "🔍 Verifying Firebase Sync Status"
echo "=================================="

# Check if emulators are connected
echo "📱 Checking emulator connections..."
adb devices | grep emulator

if [ $? -eq 0 ]; then
    echo "✅ Emulators are connected"
else
    echo "❌ No emulators found"
    exit 1
fi

echo ""
echo "🧪 Sync Test Instructions:"
echo "=========================="
echo ""
echo "1. On Emulator 5554 (Pixel Tablet):"
echo "   - Open the POS app"
echo "   - Go to 'Menu Items' or 'Categories'"
echo "   - You should see:"
echo "     • Appetizers, Main Course, Desserts, Beverages"
echo "     • Items like Bruschetta, Margherita Pizza, etc."
echo ""
echo "2. On Emulator 5556 (Medium Phone):"
echo "   - Open the POS app"
echo "   - Go to 'Menu Items' or 'Categories'"
echo "   - You should see the SAME data"
echo ""
echo "3. Test Real-time Sync:"
echo "   - On Emulator 5554: Create a new order"
echo "   - On Emulator 5556: Check 'Orders' section"
echo "   - The order should appear on both devices"
echo ""
echo "4. If data is missing:"
echo "   - Run: ./fix_firebase_sync.sh"
echo "   - Or run: source firebase_env/bin/activate && python3 setup_sample_data.py"
echo ""
echo "📊 Expected Data:"
echo "================="
echo "Categories: Appetizers, Main Course, Desserts, Beverages"
echo "Items: Bruschetta ($8.99), Margherita Pizza ($16.99), Chicken Alfredo ($18.99), Tiramisu ($9.99), Iced Latte ($4.99)"
echo "Sample Order: SYNC-001 (Sync Test Customer)"
echo ""
echo "🎯 Success Criteria:"
echo "==================="
echo "✅ Both emulators show identical menu items"
echo "✅ Both emulators show identical categories"
echo "✅ Orders created on one device appear on the other"
echo "✅ Real-time updates work between devices"
echo ""
echo "🔧 If sync is broken:"
echo "===================="
echo "1. Run: ./fix_firebase_sync.sh"
echo "2. Run: source firebase_env/bin/activate && python3 setup_sample_data.py"
echo "3. Restart both emulators"
echo "4. Test again"
echo ""
echo "📱 Both emulators should now be fully synchronized!" 